### ISSUE TITLE
nm-vpngateのサーバーリストがおかしい

### ISSUE THREAD

**Issue by sarukiti** [Hayao0819/nm-vpngate#1]
![image](https://user-images.githubusercontent.com/47556340/153804819-2b3436f4-2820-496a-a878-3d537ae65f62.png)
通常サーバーリストが出てくるであろう場所にHTMLのようなものが表示されます  
また、`nm-vpngate`を実行した場合も同様なHTMLのようなものがコンソールに表示されます  
その影響かは不明ですが、`nm-vpngate -a`を行った場合もvpnに接続されませんでした。
```
$ nm-vpngate -g
[ LOG ]: Loaded /etc/nm-vpngate.conf
[ LOG ]: Loaded /home/sarukiti/.nm-vpngate.conf
[ LOG ]: Getting server list from http://www.vpngate.net/api/iphone/ ...
[ LOG ]: 52 servers found.
[ LOG ]: Paring CSV ...
[ LOG ]: Configuring graphical user interface ...
[ LOG ]: zenity has terminated abnormally.
```

**Comment by Hayao0819** [comment]
```bash
 bash -x nm-vpngate 2>&1 | tee ~/nm-vpngate.log
```

を実行して、作成された`~/.nm-vpngate.log`をアップロードしてもらえますか？

**Comment by naoko1010hh** [comment]
Alter Linuxの仮想環境にnm-vpngateを導入後上記のコマンドを実行したログファイルです。

https://gist.github.com/naoko1010hh/a9d4a1c0968441e2ff39d63ea6cfe9b7

**Comment by naoko1010hh** [comment]
見た感じこちらの環境では正常に動作してるようです。

可能性として一時的なAPIの不調もしくは、何かしらのネットワーク環境に問題があると考えられます。
![image](https://user-images.githubusercontent.com/50263013/153848637-3bf41624-aaaf-4c27-8aaf-87812a4b3f61.png)

**Comment by sarukiti** [comment]
学内ネットワークのフィルターが原因である可能性が非常に高いので、おそらくこちらの環境が悪かったのだと思います。
大変すみませんでした
