### ISSUE TITLE
[Feature request] KDialog support.

### ISSUE THREAD

**Issue by Impeta** [Hayao0819/nm-vpngate#4]
It's not any essential of course, but just for consistency's sake on Plasma plus QT-alike environments, would it be any feasible of you implement the option to use KDialog as an alternative from Zenity? Pretty much like the winetricks does, their counterpart GUI toggle being ```--gui=kdialog```.

**Comment by Hayao0819** [comment]
OK. I'll add it.

**Comment by Hayao0819** [comment]
Almost done.  However, it looks bad and only minimal testing.

Please try it here and report it to me.


https://github.com/Hayao0819/nm-vpngate/tree/ea3b24f1ffc563b0c216dd8a00d6d6548047e971

**Comment by Hayao0819** [comment]
I thought it was an only problem depend on my environment.

I have known it and I'll try to fix it.

Until that, please use stable version `v1.0`

**Comment by Hayao0819** [comment]
Fix it in 706b6aeb43c0f072e34176ae681cd96cf465ff41

Please retry it

**Comment by Hayao0819** [comment]
Unfortunately, sorting cannot be implemented **currnetly**.

At this stage, it is implemented only by shell script, so the GUI function depends on the implementation of kdialog.
And currently kdialog doesn't support sorting like zenity.

The easiest way is to request this feature from kdialog, but I'm thinking of writing it in Python.
